### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by fi5ly** [cp6/my-idlers#31]
Hi, I get error `Illuminate \ Foundation \ Bootstrap \ HandleExceptions : 1675
handleError` on php-8.0.16 and php-8.1.3

<img src="https://bl3302files.storage.live.com/y4ms67147W5HdOTsGRdXa7jxxO2xvUwhfRGGP5A0a9umnPREgaW-aEj1fazIbsYucN_r0_ywPmC0t5fjeHu-xppmfsVDF18ct0Bh7Qt8W__goLkUnYzrReML68AM_UWk3VMFPUzWPy6spW5D412HET6a-B0RjvCoo4noKkBQMWn5iIl3x5zqkNwSNGw1tbq2lyP?width=1707&height=843&cropmode=none" />

**Comment by cp6** [comment]
What are you trying to do when this occurs and where does it occur (URL)?

**Comment by fi5ly** [comment]
Right after Signup I got an error. Url `http://localhost:8000/#F51` even I changed the url, the error remains the same

**Comment by cp6** [comment]
Alright, i seem to have been able to reproduce it...

Running `php artisan migrate` instead of `php artisan migrate:fresh --seed`
Caused the error you described. 

It has been fixed here: [8195fba66edee36284a7511454e543c368ea4d42](https://github.com/cp6/my-idlers/commit/8195fba66edee36284a7511454e543c368ea4d42)

**Comment by fi5ly** [comment]
Thanks it's fixed
