### ISSUE TITLE
YABS result undeletable

### ISSUE THREAD

**Issue by imlonghao** [cp6/my-idlers#48]
https://github.com/cp6/my-idlers/blob/6b34dd6/database/migrations/2022_05_09_114227_add_foreign_keys.php#L43-L49

In this file, `disk_speed.id` and `network_speed.id` are foreign references to `yabs.id`

And they are missing `->onDelete('cascade')`

https://github.com/cp6/my-idlers/blob/6b34dd6b8a/app/Http/Controllers/YabsController.php#L137-L144

When I delete a YABS result, the system delete the line on `yabs` first, and it will fail.

```
[2022-06-23 04:48:55] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`p7949`.`disk_speed`, CONSTRAINT `ds_fk_
yabs` FOREIGN KEY (`id`) REFERENCES `yabs` (`id`)) (SQL: delete from `yabs` where `id` = SxgQgKZw) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: In
tegrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`p7949`.`disk_speed`, CONSTRAINT `ds_fk_yabs` FOREIGN KEY (`id`) REFERENCES `yabs` (`id`)) (SQL: de
lete from `yabs` where `id` = SxgQgKZw) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:742)
[stacktrace]
```

You may want to write a new migration adding `->onDelete('cascade')` or change the order when deleting yabs result.

And BTW, it makes the VPS record undeletable too.

**Comment by cp6** [comment]
Thanks, was [fixed here (ee73ea1a31513e6e3165154e2c7ada15ea370d69)](https://github.com/cp6/my-idlers/commit/ee73ea1a31513e6e3165154e2c7ada15ea370d69)

**Comment by imlonghao** [comment]
is it a good idea changing a already existing migration?

**Comment by Decicus** [comment]
> is it a good idea changing a already existing migration?

No. Ideally you'd create a new migration file for every database modification. Especially in this scenario where the old migration was published as part of a release.

Anyone that updates from an existing installation of 2.1.1 won't have that change applied, because for them that migration technically already ran.

I suggest reverting that change to how it was (just in case it would cause any issues, but I doubt it), then creating a new migration that drops the foreign key and re-adds it correctly (which I think is the only way to add `onCascade('delete')` on an existing column).

**Comment by imlonghao** [comment]
The change to an existing migration https://github.com/cp6/my-idlers/commit/ee73ea1a31513e6e3165154e2c7ada15ea370d69 is reverted by https://github.com/cp6/my-idlers/commit/7daf609b912032de3fd8cf6578139858ae7f9d53

I tested the latest commit and it seems fixed, closing this issue now.
